version: '2.1'
services:
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "${ZOOKEEPER_PORT}:2181"
    networks:
      - chat-network

  kafka:
    image: wurstmeister/kafka
    ports:
      - "${KAFKA_PORT}:9092"
    environment:
      - KAFKA_ADVERTISED_HOST_NAME=kafka
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
    networks:
      - chat-network

  kafka-consumer:
    build:
      context: ./kafka-consumer
      dockerfile: Dockerfile
    env_file:
      - .env
    depends_on:
      postgres:
        condition: service_healthy
      kafka:
        condition: service_started
      zookeeper:
        condition: service_started
    networks:
      - chat-network

  nginx:
    image: nginx:latest
    ports:
      - "8080:80"
      - "443:443"
    volumes:
      - ./nginx.layer7.conf:/etc/nginx/nginx.conf:ro
      - /etc/letsencrypt:/etc/letsencrypt:ro  
    depends_on:
      - app1
      - app2
      - app3
    networks:
      - chat-network

  postgres:
    image: postgres:14
    environment:
      POSTGRES_DB: ${POSTGRES_DATABASE}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    env_file:
      - .env
    ports:
      - "${POSTGRES_PORT}:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DATABASE}"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - chat-network

  app1:
    build: .
    ports:
      - "8081:8080"
    env_file:
      - .env
    environment:
      - SERVER_NAME=ASIA
    networks:
      - chat-network
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_started

  app2:
    build: .
    ports:
      - "8082:8080"
    env_file:
      - .env
    environment:
      - SERVER_NAME=MIDDLE-EAST
    networks:
      - chat-network
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_started

  app3:
    build: .
    ports:
      - "8083:8080"
    env_file:
      - .env
    environment:
      - SERVER_NAME=EUROPE
    networks:
      - chat-network
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_started

  redis:
    image: redis
    ports:
      - "${REDIS_PORT}:6379"
    networks:
      - chat-network

volumes:
  postgres_data:

networks:
  chat-network:
    driver: bridge